kind: pipeline
name: train
type: docker

concurrency:
  limit: 1

steps:
  - name: install
    image: pytorch/pytorch:latest
    privileged: true
    shm_size: 1073741824
    environment:
      mount_command:
        from_secret: mount_command
      PYTHONPATH: /drone/src/
      DATA_DIR: /drone/src/data/
    commands:
      - git diff --name-only `git merge-base refs/remotes/origin/master HEAD`..HEAD | grep finetune/facenet_transfer_learning.py > /dev/null || exit 78
      - python -m pip install -q -U pip
      - pip install -q torchsummary matplotlib pytorch-metric-learning torchinfo torch torchvision tqdm Pillow facenet-pytorch
      - apt update -qq
      - apt install fonts-noto-cjk-extra -y -qq
      # - ls ./
      - mkdir -p data
      - $mount_command
      # - ls data/
      - CI=True python finetune/facenet_transfer_learning.py