kind: pipeline
name: train
type: docker

concurrency:
  limit: 1

steps:
  - name: install
    image: pytorch/pytorch:latest
    privileged: true
    shm_size: 1073741824
    environment:
      mount_command:
        from_secret: mount_command
    commands:
      - python -m pip install --upgrade pip
      - pip install torchsummary matplotlib
      - ls ./
      - mkdir -p data
      - $mount_command
      - ls data/
      - python resnet_finetune.py